/* eslint-disable @typescript-eslint/no-explicit-any -- Supabase schema types are not generated in this project. */
import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";

export const paymentStatuses = ["successful", "initialized", "pending", "failed", "abandoned", "reversed", "grant_failed"] as const;
export type AdminFilters = { id?:string; status?: string; stage?: string; date?: string; scope?: string; search?: string; page?: number; from?: string; to?: string };
export type AdminPayment = { id:string; userId:string; customer:string; email:string|null; productId:string; product:string; scope:string; stage:string; amount:number; currency:string; status:string; reference:string; grantId:string|null; grantStatus:string; accessStatus:string; createdAt:string; updatedAt:string; paidAt:string|null; matches:{matchId:string;kickoffAt:string;label:string}[] };

function startFor(date?: string) { const now = new Date(); if (date === "today") return new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString(); if (date === "7") return new Date(now.getTime()-7*864e5).toISOString(); if (date === "30") return new Date(now.getTime()-30*864e5).toISOString(); return null; }
export function isPaymentAnomaly(payment: AdminPayment, now = new Date(), staleMinutes = 30) {
  if (payment.status === "successful" && (payment.grantStatus !== "Granted" || payment.accessStatus !== "Active")) return "PAID — ACCESS ISSUE";
  if (payment.status === "grant_failed") return "GRANT FAILED";
  if (payment.status === "pending" && now.getTime()-new Date(payment.createdAt).getTime() > staleMinutes*60000) return "STALE PENDING PAYMENT";
  if (payment.status === "reversed" && payment.accessStatus === "Active") return "REVERSED PAYMENT WITH ACTIVE ACCESS";
  return null;
}

async function resolveSearch(admin:SupabaseClient,raw:string){const term=raw.replace(/[%_,()]/g,"").trim();if(!term)return[];const pattern=`%${term}%`;const [profiles,predictions,products,users]=await Promise.all([admin.from("profiles").select("id").ilike("display_name",pattern).limit(100),admin.from("public_predictions").select("public_prediction_id").or(`home_team.ilike.${pattern},away_team.ilike.${pattern}`).limit(100),admin.from("prediction_access_products").select("id").ilike("name",pattern).limit(100),admin.auth.admin.listUsers({page:1,perPage:1000})]);const matchIds=(predictions.data||[]).map((x:any)=>x.public_prediction_id);const memberships=matchIds.length?await admin.from("prediction_access_product_matches").select("product_id").in("match_id",matchIds):{data:[]};return {term,userIds:[...(profiles.data||[]).map((x:any)=>x.id),...users.data.users.filter(u=>(u.email||"").toLowerCase().includes(term.toLowerCase())).map(u=>u.id)],productIds:[...(products.data||[]).map((x:any)=>x.id),...(memberships.data||[]).map((x:any)=>x.product_id)]}}

export async function listPayments(admin: SupabaseClient, filters: AdminFilters = {}) {
  const page = Math.max(1, Number(filters.page)||1), size=25;
  const search=filters.search?await resolveSearch(admin,filters.search) as {term:string;userIds:string[];productIds:string[]}:null;
  let query = admin.from("prediction_payments").select("id,user_id,product_id,provider_reference,amount,currency,status,grant_id,created_at,updated_at,paid_at,prediction_access_products!inner(name,scope_type,prediction_stage,price_amount,prediction_access_product_matches(match_id,kickoff_at)),prediction_access_grants(id,expires_at,created_at)",{count:"exact"});
  if(filters.id) query=query.eq("id",filters.id);
  if (paymentStatuses.includes(filters.status as never)) query=query.eq("status",filters.status!);
  if (["prematch","live","halftime"].includes(filters.stage||"")) query=query.eq("prediction_access_products.prediction_stage",filters.stage!);
  if (["match","kickoff_slot"].includes(filters.scope||"")) query=query.eq("prediction_access_products.scope_type",filters.scope!);
  const start=startFor(filters.date); if(start) query=query.gte("created_at",start); if(filters.from)query=query.gte("created_at",filters.from); if(filters.to)query=query.lte("created_at",`${filters.to}T23:59:59.999Z`);
  if(search){const parts=[`provider_reference.ilike.%${search.term}%`];if(search.userIds.length)parts.push(`user_id.in.(${[...new Set(search.userIds)].join(",")})`);if(search.productIds.length)parts.push(`product_id.in.(${[...new Set(search.productIds)].join(",")})`);query=query.or(parts.join(","));}
  const result=await query.order("created_at",{ascending:false}).range((page-1)*size,page*size-1); if(result.error) throw result.error;
  const rows=result.data as unknown as any[]; const userIds=[...new Set(rows.map(r=>r.user_id))]; const matchIds=[...new Set(rows.flatMap(r=>r.prediction_access_products.prediction_access_product_matches.map((m:any)=>m.match_id)))];
  const [profiles,predictions,users]=await Promise.all([userIds.length?admin.from("profiles").select("id,display_name").in("id",userIds):Promise.resolve({data:[]}),matchIds.length?admin.from("public_predictions").select("public_prediction_id,home_team,away_team,league").in("public_prediction_id",matchIds):Promise.resolve({data:[]}),Promise.all(userIds.map(id=>admin.auth.admin.getUserById(id)))]);
  const profileMap=new Map((profiles.data||[]).map((p:any)=>[p.id,p.display_name])); const predictionMap=new Map((predictions.data||[]).map((p:any)=>[p.public_prediction_id,`${p.home_team} vs ${p.away_team}`])); const emailMap=new Map(users.map((u,i)=>[userIds[i],u.data.user?.email||null]));
  const payments:AdminPayment[]=rows.map(r=>{const grant=r.prediction_access_grants; const active=Boolean(grant&&(!grant.expires_at||new Date(grant.expires_at)>new Date())); return {id:r.id,userId:r.user_id,customer:profileMap.get(r.user_id)||`User …${r.user_id.slice(-8)}`,email:emailMap.get(r.user_id)||null,productId:r.product_id,product:r.prediction_access_products.name,scope:r.prediction_access_products.scope_type,stage:r.prediction_access_products.prediction_stage,amount:Number(r.amount),currency:r.currency,status:r.status,reference:r.provider_reference,grantId:r.grant_id,grantStatus:grant?"Granted":"Missing",accessStatus:active?"Active":"Inactive",createdAt:r.created_at,updatedAt:r.updated_at,paidAt:r.paid_at,matches:r.prediction_access_products.prediction_access_product_matches.map((m:any)=>({matchId:m.match_id,kickoffAt:m.kickoff_at,label:predictionMap.get(m.match_id)||m.match_id}))}});
  return {payments,count:result.count||0,page,pages:Math.max(1,Math.ceil((result.count||0)/size))};
}

export async function getOverview(admin:SupabaseClient){const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()).toISOString(),week=new Date(now.getTime()-7*864e5).toISOString();const [{data:payments},{data:grants}]=await Promise.all([admin.from("prediction_payments").select("amount,currency,status,grant_id,created_at,updated_at,product_id,user_id,id,provider_reference,paid_at").gte("created_at",week),admin.from("prediction_access_grants").select("id,expires_at,prediction_access_products!inner(prediction_stage)")]);const rows=payments||[];const todayRows=rows.filter((p:any)=>p.created_at>=today);const revenue=(xs:any[])=>xs.filter(p=>p.status==="successful").reduce((n,p)=>n+Number(p.amount),0);const active=(grants||[]).filter((g:any)=>!g.expires_at||new Date(g.expires_at)>now);return {today:{revenue:revenue(todayRows),successful:todayRows.filter((p:any)=>p.status==="successful").length,pending:todayRows.filter((p:any)=>p.status==="pending").length,failed:todayRows.filter((p:any)=>["failed","abandoned","grant_failed"].includes(p.status)).length},week:{revenue:revenue(rows),successful:rows.filter((p:any)=>p.status==="successful").length},access:{prematch:active.filter((g:any)=>g.prediction_access_products.prediction_stage==="prematch").length,live:active.filter((g:any)=>g.prediction_access_products.prediction_stage==="live").length,halftime:active.filter((g:any)=>g.prediction_access_products.prediction_stage==="halftime").length}}}

export async function listGrants(admin:SupabaseClient,stage?:string,status?:string){let q=admin.from("prediction_access_grants").select("id,user_id,product_id,granted_at,created_at,expires_at,prediction_access_products!inner(name,scope_type,prediction_stage,prediction_access_product_matches(match_id,kickoff_at)),prediction_payments(id,status,provider_reference)").order("created_at",{ascending:false}).limit(100);if(["prematch","live","halftime"].includes(stage||""))q=q.eq("prediction_access_products.prediction_stage",stage!);const {data,error}=await q;if(error)throw error;const now=new Date();return (data as unknown as any[]).map(g=>({...g,prediction_payments:Array.isArray(g.prediction_payments)?g.prediction_payments:g.prediction_payments?[g.prediction_payments]:[]})).filter(g=>status==="active"?(!g.expires_at||new Date(g.expires_at)>now):status==="past"?(g.expires_at&&new Date(g.expires_at)<=now):true)}
